version: "2"
linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    gosec:
      excludes:
        - G104
    revive:
      rules:
        - name: exported
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
